In [2]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
X = np.array([[30], [35], [40], [45], [50], [55], [60], [65], [70], [75], [80], [85], [90]], dtype=float)
y = np.array([[0], [0], [0], [0], [0], [1], [0], [1], [1], [1], [1], [1], [1]], dtype=float)

In [4]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-1.60356745],
       [-1.33630621],
       [-1.06904497],
       [-0.80178373],
       [-0.53452248],
       [-0.26726124],
       [ 0.        ],
       [ 0.26726124],
       [ 0.53452248],
       [ 0.80178373],
       [ 1.06904497],
       [ 1.33630621],
       [ 1.60356745]])

In [5]:
model = Sequential()
model.add(Dense(10, activation='relu', input_shape=(1,)))
model.add(Dense(1, activation='sigmoid'))

c:\Users\dvica\PycharmProjects\PythonProject\hw_or_jup_note_book\tf310\lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_scaled, y, epochs=100, verbose=0)

In [7]:
income_58 = scaler.transform(np.array([[58]]))
income_58

array([[-0.1069045]])

array([[-0.1069045]])

In [8]:
prediction = model.predict(income_58)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


array([[0.517264]], dtype=float32)

array([[0.517264]], dtype=float32)